### ISSUE TITLE
Non-project mails

### ISSUE THREAD

**Issue by saz** [luismaia/redmine_email_fetcher#9]
Right now, I'll need to have two cronjobs running. One for redmine_email_fetcher, the other one for fetching non-project mails, for example, a response to a notification sent by redmine.

As the project is a required field, I'm not able to set up a configuration to fetch non-project mails.

For this, the arguments to redmine:email:receive_imap are host, ssl, port, no_account_notice, move_on_success, unknown_user, no_permission_check.
The project, tracker and category is available in the message body.

It would be great, if you can remove the requirement for a project or add an option, where the project can be unset.

Some more information for this: http://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails#Target-project

**Comment by saz** [comment]
Oh by the way, I'm aware that I can just select any project and add project to allow_override, but I don't find this a good way of handling this case, as this might lead to imports of a message for a project, which shouldn't be in this project, if the project is missing.

**Comment by luismaia** [comment]
Hi @saz 

Sorry for the later reply.

To handle a similar situation I created filters in the email account. Each filter is forwarding the emails to the appropriate folder (e.g. IT, NO_ACTION, etc.) or leaving the email in the INBOX folder if no filter is applied to it.

Then using this plugin, I have one configuration per FOLDER in the email (but only the folders I really want to import emails from).
Looking to the previous example, I would have a configuration to scan emails from folder IT to Redmine project "PROJ1" and another configuration to scan emails from folder INBOX to Redmine project "PROJ2".

The emails I know are not supposed to be pushed to Redmine are send to folder NO_ACTION.

Having that said, I don't think that is a good idea to remove Project as a mandatory field, because that would mean that I would have to add a default Redmine project to the crontab job (going against the goal of this plugin - that is remove email and Redmine projects information from the crontab).

Can you use filters in your email? Does this approach solves your problem?
Did I understand correctly your question/feature request?

**Comment by saz** [comment]
I'm talking about responses to notification mails. Those responses are sent to one e-mail address (emission email address in Redmine settings -> Email notifications), as all of them (for every project) are coming from this address. In such a case, I'm not able to select a project, as there is no such thing as "the one right project".
The project is mentioned in the email itself and this information is used by the importer to select the right project.

Right now, I've just selected a random project, which is bad. For example, if a user removes issue meta information from the response, this will create an issue inside a project, where this email doesn't belong at all.

I hope, I was able to clear things up a little bit.
